export default {

    mainurl: 'http://203.109.113.162:9098/castpro/public/api/',   ///Developer RL
    // mainurl: 'http://203.109.113.162:5055/castpro/public/api/',   ///Testing URL
    // mainurl: 'http://ec2-52-15-140-180.us-east-2.compute.amazonaws.com/castpro/public/api/',   ///Testing URL
    // Profile API
    Register: 'register',
    login: 'login',
    Facebooklogin: 'facebookLogin',
    Upload: 'testAPI',
    userVerifyotp: 'userVerify',
    Chnagepassword: 'changePassword',
    Actorprofile: 'getProfile',
    Directorgetprofile: 'getDirectorProfile',
    Directorupdateprofile: 'updateDirectorDetails',
    Termsandcondition: 'getTermsAndConditions',
    Getsocialmedia: 'getSocialMedia',
    GetStateAndCity: 'getStateAndCities',
    UpdateActorBio: 'updateActorBio',
    ActorPhootAddDelete: 'actorImageAddDelete',
    ActorVideo: 'actorVideoAddDelete',
    ActorUpdateworklink: 'updateActorWorkLinks',
    UpdateDirectorAcceptTCStatus: 'updateDirectorAcceptTCStatus',
    Getcountrycode: 'getCountriesCode',
    GetLanguage: 'getLanguage',
    GetSkill: 'getSkill',
    AllProject: 'getAllProjects',
    Directorsearch: 'directorSearchArtist',
    GetDirectorList: 'getDirectorList',
    CreateProject: 'project/create',
    ViewProjectDetail: 'viewProjectById',
    CreateRole: 'role/create',
    RoleDetail: 'roleDetails',
    Roledelete: 'role/delete',
    RoleAuditionlist: 'viewRoleAudition',
    ViewAudition: 'viewRoleAuditionDetail',
    ProjectUpdate: 'project/update',
    RoleUpdate: 'role/update',
    AuditionComment: 'auditionComment',
    Shortlisted: 'shortlistAudition',
    ProfileReqeustlist: 'profileRequestList',
    ViewartistProfile: 'viewArtistProfile',
    RequestForProfile: 'requestForProfile',
    Auditionrequestlist: 'getAuditionRequestList',
    ShortlistRequest: 'getShortlistAudition',
    GetRole: 'role',
    SendAuditionrequest: 'sendAuditionRequest',
    UpdateWorklink: 'updateDirectorKeyProject',
    GetNotification: 'getNotificationList',
    ReadNotificaion: 'readNotification',
    Unreadcoiunt: 'getUnreadNotificationListCount',
    Aboutus:'getAboutUs',
    Notification:'updateNotificationStatus',

    DashBoard:'getDirectorDashboard',
    ProjectListing:'projectListing',
    ProjectType:'getProjectTypes',
    GetLanguage: 'getLanguage',
    Getcountrycode:'getCountryStatesCities',
    Auditionrequestbyroleid:'auditionRequestListingByRoleId',
    ShortlistingbyRole:'shortlistAuditionListingByRoleId',
    Auditionlisting:'auditionListingByRoleId'
};

